import os
import smtplib
import glob
from email.mime.text import MIMEText
from dotenv import load_dotenv

load_dotenv()

EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASS = os.getenv("EMAIL_PASS")
QUEUE_DIR = "/Users/mtb/ready_to_send"
ARCHIVE_DIR = "/Users/mtb/sent_archive"

def flush_outbound_queue():
    if not EMAIL_USER or not EMAIL_PASS:
        print("✗ Outbound Mailer Error: Missing .env credentials.")
        return

    # Find all outbound text assets generated by the agent
    email_files = glob.glob(os.path.join(QUEUE_DIR, "*.txt"))
    if os.path.exists(self.token_path):
            with open(self.token_path, 'rb') as token:
                self.creds = pickle.load(token)

try if not self.creds or not self.creds.valid:
            if self.creds and self.creds.expired and self.creds.refresh_token:
                self.creds.refresh(Request())
            else:
                if not os.path.exists(self.credentials_path):
                    print(f"🛑 CRITICAL: Cannot find {self.credentials_path}")
                    print("Please download your OAuth 2.0 Client ID JSON from Google Cloud Console and save it there.")
                    exit(1)
                
                # Fire up the browser for the user to approve
                flow = InstalledAppFlow.from_client_secrets_file(self.credentials_path, SCOPES)
                self.creds = flow.run_local_server(port=0)
            
            # Save the credentials for the next run
            with open(self.token_path, 'wb') as token:
                pickle.dump(self.creds, token)
        
        print("✅ Gmail OAuth2 Authentication Successful! Token saved.")
        return build('gmail', 'v1', credentials=self.creds)

if __name__ == "__main__":
    GmailClient()

                # Parse the structured blocks generated by Qwen3
                lines = content.split("\n")
                to_email = ""
                subject = "Partnership / Project Inquiry"
                body_lines = []
                
                for line in lines:
                    if line.upper().startswith("TO:"):
                        to_email = line.split(":", 1)[1].strip()
                    elif line.upper().startswith("SUBJECT:"):
                        subject = line.split(":", 1)[1].strip()
                    else:
                        body_lines.append(line)

                body = "\n".join(body_lines).strip()

                if not to_email or "@" not in to_email:
                    print(f"  ✗ Skipping {os.path.basename(file_path)}: Invalid 'TO:' email format.")
                    continue

                # Construct MIME message
                msg = MIMEText(body)
                msg["Subject"] = subject
                msg["From"] = EMAIL_USER
                msg["To"] = to_email

                # Fire outbound transmission
                server.sendmail(EMAIL_USER, to_email, msg.as_string())
                print(f"  ✓ Pitch successfully emailed to: {to_email}")

                # Archive the file so we never double-send
                os.rename(file_path, os.path.join(ARCHIVE_DIR, os.path.basename(file_path)))

            except Exception as file_err:
                print(f"  ✗ Failed to process individual file {file_path}: {file_err}")

        server.quit()
    except Exception as server_err:
        print(f"✗ SMTP Connection Failed: {server_err}")

if __name__ == "__main__":
    flush_outbound_queue()
