/**
 * Deal-flow pipeline constants (home.md §6).
 * Static representative constants — the bundled dataset contains no pipeline
 * records. Styled like live data; the illustrative-telemetry footnote stays.
 */

export interface PipelineStage {
  id: string
  label: string
  value: number
  display: string
  sub: string
  /** conversion label on the edge INTO the next stage */
  edgeToNext?: string
  tooltip: string
}

export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: 'leads',
    label: 'LEADS SOURCED',
    value: 1284,
    display: '1,284',
    sub: 'SCRAPER FEED · 30D',
    edgeToNext: 'CONV 24.3%',
    tooltip: 'Leads sourced — label, sync and playlist contacts harvested by the Omni-Studio scraper feed over the last 30 days.',
  },
  {
    id: 'pitches',
    label: 'PITCHES SENT',
    value: 312,
    display: '312',
    sub: 'AUTO-GENERATED EMAILS',
    edgeToNext: 'CONV 12.2%',
    tooltip: 'Pitches sent — personalized outreach emails generated by the Omni-Studio pitch engine.',
  },
  {
    id: 'negotiation',
    label: 'IN NEGOTIATION',
    value: 38,
    display: '38',
    sub: 'ACTIVE THREADS',
    edgeToNext: 'CONV 18.4%',
    tooltip: 'In negotiation — open threads with counterparts actively discussing terms.',
  },
  {
    id: 'closed',
    label: 'DEALS CLOSED',
    value: 7,
    display: '7',
    sub: 'PLACEMENTS + LICENSES',
    tooltip: 'Deals closed — signed placements and licenses in the current window.',
  },
]

export const PIPELINE_VALUE = '$48,200'
export const PIPELINE_VALUE_SUB = 'OPEN + CLOSED-WON · 30D'
export const PIPELINE_FOOTNOTE = 'SESSION TELEMETRY · ILLUSTRATIVE — ECHOES DASHBOARD.PY'
