#!/bin/bash
echo "=== Studio Pipeline Status ==="
echo ""
echo "Alerts Watcher:"
launchctl list | grep com.voltrecords.alerts || echo "  NOT RUNNING"
echo ""
echo "Studio Agent:"
launchctl list | grep com.voltrecords.studioagent || echo "  NOT RUNNING"
echo ""
echo "=== Recent Activity ==="
echo "--- alerts_watcher.log (last 5 lines) ---"
tail -5 ~/Omni-Studio/logs/alerts_watcher.log 2>/dev/null || echo "  no log yet"
echo ""
echo "--- agent.log (last 5 lines) ---"
tail -5 ~/Omni-Studio/logs/agent.log 2>/dev/null || echo "  no log yet"
